# Generated by Django 3.2.4 on 2021-07-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_follower_follower'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user', 'follower')},
        ),
    ]
